### PR TITLE
Close subscribers on errors during initial connection.

### LINKED ISSUE #958: Subscribers are still associated to a previous publisher room if it was destroyed while waiting for it to be connected
If a subscriber connection is tried to be established before the publisher connection is ready [the signaling server detects the problem and tries again once the publisher connection is finally established](https://github.com/strukturag/nextcloud-spreed-signaling/blob/32a86fdd762af669c44c4f7d00676e834581f244/mcu_janus_subscriber.go#L195-L215). Independently of that, [the Talk UI will also request a new offer for the subscriber connection if it was not established after ten seconds](https://github.com/nextcloud/spreed/blob/f01a07c795eed4c11b2fffc9b7fcc38113718cd2/src/utils/webrtc/webrtc.js#L352-L356). However, if the publisher participant leaves the call before the publisher connection is established and then joins again the subscriber will still try to establish the connection with the previous Janus room. Example logs (note that some changes were added to Talk code to ease triggering this, see details in _How to test_ below):
<details>

```
mcu_janus.go:563: Attached video as publisher 3527173489232670 to plugin janus.plugin.videoroom in session 233376644158890
mcu_janus.go:549: Created room 2982065707994312 {janus.plugin.videoroom map[permanent:false room:2982065707994312 videoroom:created]}
mcu_janus.go:630: Publisher oh6B8AGQ12oIqX3BPvJBfLGwirU_9VOfpSLFRRsGkLJ8PT1BZTJZY3h4eWVIekZKVUdaRVdVZUhtZi1ONU94dnlwX3FONzNZdHVQMHB1MzRremZSd1hZQjl8NjQxODg1MzQ3MQ== is using handle 3527173489232670
clientsession.go:946: Publishing video as 1 for session oh6B8AGQ12oIqX3BPvJBfLGwirU_9VOfpSLFRRsGkLJ8PT1BZTJZY3h4eWVIekZKVUdaRVdVZUhtZi1ONU94dnlwX3FONzNZdHVQMHB1MzRremZSd1hZQjl8NjQxODg1MzQ3MQ==

room.go:789: Session oh6B8AGQ12oIqX3BPvJBfLGwirU_9VOfpSLFRRsGkLJ8PT1BZTJZY3h4eWVIekZKVUdaRVdVZUhtZi1ONU94dnlwX3FONzNZdHVQMHB1MzRremZSd1hZQjl8NjQxODg1MzQ3MQ== joined call 3mynk2ri

mcu_janus.go:685: Attached subscriber to room 2982065707994312 of publisher oh6B8AGQ12oIqX3BPvJBfLGwirU_9VOfpSLFRRsGkLJ8PT1BZTJZY3h4eWVIekZKVUdaRVdVZUhtZi1ONU94dnlwX3FONzNZdHVQMHB1MzRremZSd1hZQjl8NjQxODg1MzQ3MQ== in plugin janus.plugin.videoroom in session 233376644158890 as 5910052484549110
clientsession.go:1024: Subscribing video from oh6B8AGQ12oIqX3BPvJBfLGwirU_9VOfpSLFRRsGkLJ8PT1BZTJZY3h4eWVIekZKVUdaRVdVZUhtZi1ONU94dnlwX3FONzNZdHVQMHB1MzRremZSd1hZQjl8NjQxODg1MzQ3MQ== as 2 in session ogfFSvWbooOmn-7FhLPYtIbmSa4rHvFvpr_n1zcpXWl8PT1ndTBuV01RVmlCMzluMTFNMUpmb250cUdjcXoxSncyTkF6ZXFWR0xlR0dYRjJqRmNDU01tYk58NzQxODg1MzQ3MQ==
[ERR] [plugins/janus_videoroom.c:janus_videoroom_handler:10142] No such feed (1)
mcu_janus_subscriber.go:202: Publisher oh6B8AGQ12oIqX3BPvJBfLGwirU_9VOfpSLFRRsGkLJ8PT1BZTJZY3h4eWVIekZKVUdaRVdVZUhtZi1ONU94dnlwX3FONzNZdHVQMHB1MzRremZSd1hZQjl8NjQxODg1MzQ3MQ== not sending yet for video, wait and retry to join room 2982065707994312 as subscriber

hub.go:2673: Could not send MCU message &{Type:requestoffer Sid: RoomType:video Payload:map[] Bitrate:0 AudioCodec: VideoCodec: VP9Profile: H264Profile: offerSdp:<nil> answerSdp:<nil>} for session ogfFSvWbooOmn-7FhLPYtIbmSa4rHvFvpr_n1zcpXWl8PT1ndTBuV01RVmlCMzluMTFNMUpmb250cUdjcXoxSncyTkF6ZXFWR0xlR0dYRjJqRmNDU01tYk58NzQxODg1MzQ3MQ== to oh6B8AGQ12oIqX3BPvJBfLGwirU_9VOfpSLFRRsGkLJ8PT1BZTJZY3h4eWVIekZKVUdaRVdVZUhtZi1ONU94dnlwX3FONzNZdHVQMHB1MzRremZSd1hZQjl8NjQxODg1MzQ3MQ==: context deadline exceeded
[ERR] [plugins/janus_videoroom.c:janus_videoroom_handler:10142] No such feed (1)
mcu_janus_subscriber.go:202: Publisher oh6B8AGQ12oIqX3BPvJBfLGwirU_9VOfpSLFRRsGkLJ8PT1BZTJZY3h4eWVIekZKVUdaRVdVZUhtZi1ONU94dnlwX3FONzNZdHVQMHB1MzRremZSd1hZQjl8NjQxODg1MzQ3MQ== not sending yet for video, wait and retry to join room 2982065707994312 as subscriber
clientsession.go:505: Session oh6B8AGQ12oIqX3BPvJBfLGwirU_9VOfpSLFRRsGkLJ8PT1BZTJZY3h4eWVIekZKVUdaRVdVZUhtZi1ONU94dnlwX3FONzNZdHVQMHB1MzRremZSd1hZQjl8NjQxODg1MzQ3MQ== left call 3mynk2ri

mcu_janus_publisher.go:145: Room 2982065707994312 destroyed
mcu_janus_publisher.go:64: Publisher 3527173489232670: associated room has been destroyed, closing

hub.go:2673: Could not send MCU message &{Type:requestoffer Sid: RoomType:video Payload:map[] Bitrate:0 AudioCodec: VideoCodec: VP9Profile: H264Profile: offerSdp:<nil> answerSdp:<nil>} for session ogfFSvWbooOmn-7FhLPYtIbmSa4rHvFvpr_n1zcpXWl8PT1ndTBuV01RVmlCMzluMTFNMUpmb250cUdjcXoxSncyTkF6ZXFWR0xlR0dYRjJqRmNDU01tYk58NzQxODg1MzQ3MQ== to oh6B8AGQ12oIqX3BPvJBfLGwirU_9VOfpSLFRRsGkLJ8PT1BZTJZY3h4eWVIekZKVUdaRVdVZUhtZi1ONU94dnlwX3FONzNZdHVQMHB1MzRremZSd1hZQjl8NjQxODg1MzQ3MQ==: context deadline exceeded

mcu_janus.go:563: Attached video as publisher 3279797714020914 to plugin janus.plugin.videoroom in session 233376644158890
mcu_janus.go:549: Created room 6518606511619223 {janus.plugin.videoroom map[permanent:false room:6518606511619223 videoroom:created]}
mcu_janus.go:630: Publisher oh6B8AGQ12oIqX3BPvJBfLGwirU_9VOfpSLFRRsGkLJ8PT1BZTJZY3h4eWVIekZKVUdaRVdVZUhtZi1ONU94dnlwX3FONzNZdHVQMHB1MzRremZSd1hZQjl8NjQxODg1MzQ3MQ== is using handle 3279797714020914
clientsession.go:946: Publishing video as 3 for session oh6B8AGQ12oIqX3BPvJBfLGwirU_9VOfpSLFRRsGkLJ8PT1BZTJZY3h4eWVIekZKVUdaRVdVZUhtZi1ONU94dnlwX3FONzNZdHVQMHB1MzRremZSd1hZQjl8NjQxODg1MzQ3MQ==

hub.go:2673: Could not send MCU message &{Type:requestoffer Sid: RoomType:video Payload:map[] Bitrate:0 AudioCodec: VideoCodec: VP9Profile: H264Profile: offerSdp:<nil> answerSdp:<nil>} for session ogfFSvWbooOmn-7FhLPYtIbmSa4rHvFvpr_n1zcpXWl8PT1ndTBuV01RVmlCMzluMTFNMUpmb250cUdjcXoxSncyTkF6ZXFWR0xlR0dYRjJqRmNDU01tYk58NzQxODg1MzQ3MQ== to oh6B8AGQ12oIqX3BPvJBfLGwirU_9VOfpSLFRRsGkLJ8PT1BZTJZY3h4eWVIekZKVUdaRVdVZUhtZi1ONU94dnlwX3FONzNZdHVQMHB1MzRremZSd1hZQjl8NjQxODg1MzQ3MQ==: context deadline exceeded
[ERR] [plugins/janus_videoroom.c:janus_videoroom_access_room:4690] No such room (2982065707994312)
mcu_janus_subscriber.go:200: Publisher oh6B8AGQ12oIqX3BPvJBfLGwirU_9VOfpSLFRRsGkLJ8PT1BZTJZY3h4eWVIekZKVUdaRVdVZUhtZi1ONU94dnlwX3FONzNZdHVQMHB1MzRremZSd1hZQjl8NjQxODg1MzQ3MQ== not created yet for video, wait and retry to join room 2982065707994312 as subscriber
```

</details>

Note that this is not reproducible with Janus 0.14. In this case establishing the subscriber connection succeeds even if the publisher connection is not ready yet. No media is transmitted in that case (if the publisher has video enabled in the receiver participant nothing will be shown, but there will be no loading spinner either) until the publisher connection is finally established. Example logs:
<details>

```
mcu_janus.go:563: Attached video as publisher 2406940952833699 to plugin janus.plugin.videoroom in session 3896207650004009
mcu_janus.go:549: Created room 3396674090986476 {janus.plugin.videoroom map[permanent:false room:3396674090986476 videoroom:created]}
mcu_janus.go:630: Publisher jyUMvgZ3Zr6LK_yKcI5iIE1cXjwY_2LKc4uz5z3ecfV8PT1nUlR2NEYxYmhRRHMzUXZ5MVotcFhYYldQTFpMMk9rd0NDZGtFeWM1VDFPSHBwOHNHRFdWXzF8NDg0Nzg1MzQ3MQ== is using handle 2406940952833699
clientsession.go:946: Publishing video as 7 for session jyUMvgZ3Zr6LK_yKcI5iIE1cXjwY_2LKc4uz5z3ecfV8PT1nUlR2NEYxYmhRRHMzUXZ5MVotcFhYYldQTFpMMk9rd0NDZGtFeWM1VDFPSHBwOHNHRFdWXzF8NDg0Nzg1MzQ3MQ==

room.go:789: Session jyUMvgZ3Zr6LK_yKcI5iIE1cXjwY_2LKc4uz5z3ecfV8PT1nUlR2NEYxYmhRRHMzUXZ5MVotcFhYYldQTFpMMk9rd0NDZGtFeWM1VDFPSHBwOHNHRFdWXzF8NDg0Nzg1MzQ3MQ== joined call 3mynk2ri
Creating new handle in session 3896207650004009: 8269411049945334; 0x7fd5a8003750 0x7fd5a8008d00
mcu_janus.go:685: Attached subscriber to room 3396674090986476 of publisher jyUMvgZ3Zr6LK_yKcI5iIE1cXjwY_2LKc4uz5z3ecfV8PT1nUlR2NEYxYmhRRHMzUXZ5MVotcFhYYldQTFpMMk9rd0NDZGtFeWM1VDFPSHBwOHNHRFdWXzF8NDg0Nzg1MzQ3MQ== in plugin janus.plugin.videoroom in session 3896207650004009 as 8269411049945334
clientsession.go:1024: Subscribing video from jyUMvgZ3Zr6LK_yKcI5iIE1cXjwY_2LKc4uz5z3ecfV8PT1nUlR2NEYxYmhRRHMzUXZ5MVotcFhYYldQTFpMMk9rd0NDZGtFeWM1VDFPSHBwOHNHRFdWXzF8NDg0Nzg1MzQ3MQ== as 8 in session TdZUcXkUN6vMV19AR1qGDHykg3e5bEVNsVeqDj5_BrB8PT1nbHlSRzd6U00xNU5wd09GR2RNR0x4OUc2RnJOM2tIbTB5MGJaT0VpWEYzY0F4dVpGTENfdkF8Mjg0Nzg1MzQ3MQ==

mcu_janus_client.go:165: Started listener &{{janus.plugin.videoroom map[room:3396674090986476 started:ok videoroom:event]} map[] 3896207650004009 8269411049945334}
mcu_janus_subscriber.go:78: Subscriber 8269411049945334 received connected

mcu_janus_publisher.go:87: Publisher 2406940952833699 received connected
```

</details>

## How to test

- Setup Talk HPB with Janus 1.X
- Delay [handling the answer for the publisher connection](https://github.com/nextcloud/spreed/blob/64622149776d62b088a4b64145d5a4b4901921fa/src/utils/webrtc/simplewebrtc/peer.js#L512-L514) by wrapping it in a `setTimeout`:
```
setTimeout(() => {
    this.pc.setRemoteDescription(answer).catch(function(error) {
        console.warn('setRemoteDescription for answer failed: ', error)
    })
}, 15000)
```
- Disable retrying to establish a publisher connection in Talk by commenting https://github.com/nextcloud/spreed/blob/f01a07c795eed4c11b2fffc9b7fcc38113718cd2/src/utils/webrtc/webrtc.js#L151-L170
- Log in Nextcloud
- Open Talk
- Create a group conversation and add another user
- Start a call without microphone nor camera (that is, none selected, not just disabled, so there is no publisher for this participant and logs are easier to check)
- In a private window, log in as the other user
- Open Talk
- Open the conversation
- Join the call with microphone and/or camera
- After 5 seconds or so, leave the call (so the publisher connection was not established, but the other participant already tried to establish a subscriber connection)
- Join the call again
- Wait until the publisher connection is established

### Expected result

The subscriber connection is established

### Actual result

The subscriber connection is never established, even if tried again and again; if another participant joins the call (or the original one leaves and joins again) that participant will be able to establish a subscriber connection

### PR DESCRIPTION
**Pull request by fancycode**
This makes sure the subscriber is not cached but created newly which will fetch the publisher room id again in case it was changed since the initial subscription.

Fixes #958

CC @danxuliu

### CODE REVIEW

File: mcu_janus_subscriber.go [hunk 1]
```diff
@@ -198,6 +198,9 @@ retry:
 			switch error_code {
 			case JANUS_VIDEOROOM_ERROR_NO_SUCH_ROOM:
 				log.Printf("Publisher %s not created yet for %s, wait and retry to join room %d as subscriber", p.publisher, p.streamType, p.roomId)
```
Comment (danxuliu) [inline mcu_janus_subscriber.go:200]: Is the log message still valid with the change below or should it be adjusted?

**Review by danxuliu — COMMENTED** [review]
Other than the comment, tested and works :+1:

Thanks!
